version: '3.7'

services:
  tvchart:
    build: .
    container_name: backend
    command: sh entrypoint.prod.sh
    volumes:
      - .:/usr/src/app/
    expose:
      - 8000
    env_file:
      - .env

  nginx:
    image: library/nginx:latest
    ports:  # host-port 8111 (:) container-port 80
      - "8111:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
