# Generated by Django 4.2.5 on 2023-11-22 15:06

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_channel_text',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='About channel text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_channel_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='About channel title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='distributor_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distributor address'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='distributor_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='distributor_intro',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Distributor intro'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='distributor_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distributor name'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='distributor_phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Distributor phone'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='distributor_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distributor title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offer_for_sponsor_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offer_for_sponsor_img_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offer_for_sponsor_img_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sponsors contact name'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offer_for_sponsor_img_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Manager title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offer_for_sposnsors_text',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Offer for sponsors text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='offer_for_sposnsors_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Offer fo sponsors'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_facebook_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facebook', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_facebook_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook address'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_instagram_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instagram', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_instagram_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram address'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Social title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_youtube_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='youtube', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_youtube_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Youtube address'),
        ),
    ]
