# Generated by Django 4.2.5 on 2023-11-22 18:13

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_about_channel_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='about_channel_text',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='О канале текст'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_channel_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='О канале заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='distributor_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дистрибутор название'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='distributor_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Дистрибутор email'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='distributor_intro',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Дистрибуция текст'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='distributor_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дистрибутор название'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='distributor_phone',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Дистрибутор телефон'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='distributor_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дистрибуция заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='offer_for_sponsor_img_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='для спонсоров контактный Email'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='offer_for_sponsor_img_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Контакт для спонсоров'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='offer_for_sponsor_img_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Контакт для спонсоров менеджер'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='offer_for_sposnsors_text',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Для спонсоров текст'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='offer_for_sposnsors_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Для спонсоров заголовок'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='social_facebook_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook адрес'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='social_instagram_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram адрес'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='social_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Соц.сети название'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='social_youtube_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Youtube адрес'),
        ),
    ]
