# Generated by Django 4.2.5 on 2023-11-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartline',
            name='program_genre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Жанр программы'),
        ),
        migrations.AlterField(
            model_name='chartline',
            name='program_title',
            field=models.CharField(max_length=200, verbose_name='Название программы'),
        ),
    ]
